# This is the Action that is used to smoke test to make sure that the app can install, build, lint, etc..

name: Smoke Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'
    
jobs:
  setup-bickerin-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
  check-bickerin-lint:
    runs-on: ubuntu-latest
    needs: setup-bickerin-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run lint

  check-bickerin-unit-tests:
    runs-on: ubuntu-latest
    needs: setup-bickerin-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run test

  check-bickerin-build:
    runs-on: ubuntu-latest
    needs: setup-bickerin-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run build-app