# This is a basic workflow to help you get started with Actions

name: Smoke Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'
    
jobs:
  setup-bickerin-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - name: Zip artifact for other jobs
        run: zip node_modules.zip ./node_modules -r
      - uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.zip
          if-no-files-found: error
  check-bickerin-lint:
    runs-on: ubuntu-latest
    needs: setup-bickerin-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules.zip
      - run: ls -alt
      - name: Unzip artifact for other jobs
        run: unzip ./node_modules.zip
      - run: npm run lint

  check-bickerin-build:
    runs-on: ubuntu-latest
    needs: setup-bickerin-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules.zip
      - name: Unzip artifact for other jobs
        run: unzip node_modules.zip
      - run: npm run build
